import mongoose from 'mongoose';

const DeviceTokenSchema = new mongoose.Schema({
  userId: {
    type: String, // UUID from SQL users table
    required: true,
    index: true
  },
  deviceId: {
    type: String, // unique per device (generated by client)
    required: true
  },
  deviceType: {
    type: String, // 'android', 'ios', 'web'
    enum: ["android", "ios", "web"],
    required: true
  },
  fcmToken: {
    type: String,
    required: true
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

DeviceTokenSchema.index({ userId: 1, deviceId: 1 }, { unique: true }); // avoids the duplicate deviceids
const DeviceToken = mongoose.model("DeviceToken", DeviceTokenSchema);

export default DeviceToken;